# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c14a98c48a2175619293a0c8824fb941adcea516fcb8b10aecf60d7f4cc8bd7f36894feda7e60f94c06a0651fdc4ba4d784ca4e9eae31b3662b77243c2de367

test:
  secret_key_base: 4ad899b906a06d0decdfcffbdd8b3bae9120cb07829f88472d2c137ad858715206f69763dff8d41a77af875a01f914e991098652f2e71ae921ff1fdeb329f973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
